name: Run APP Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0/10 * * * *"  # 整点运行
  push:
    branches:
      - main
jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # 设置你希望使用的 Python 版本，建议使用稳定版本

      - name: Create .env file from environment variable
        run: echo "$ENV" > .env
        env:
            ENV: ${{ secrets.ENV }}  # 从GitHub Secrets中获取环境变量

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          # 安装 ChromeDriver
          CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f3 | cut -d '.' -f1)
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -q -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
      - name: 运行脚本
        run: |
          python main_app.py