name: Run Crawl Script

on:
  workflow_dispatch:
  schedule:
#    - cron: "0 9-23 * * *"  # 9点-23点运行
#    - cron: "0 1-15 * * *"  # 按 UTC 时间的 1 点到 15 点运行，即北京时间 9 点到 23 点
    - cron: "0 * * * *"  # 整点运行
  push:
    branches:
      - main
jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # 设置你希望使用的 Python 版本，建议使用稳定版本

      - name: Create .env file from environment variable
        run: echo "$ENV" > .env
        env:
            ENV: ${{ secrets.ENV }}  # 从GitHub Secrets中获取环境变量

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行脚本
        run: |
          python main.py